import TanStackQueryWrapper from "@/components/setupComponents/tanstackQuery/tanstackWrapper";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { LanguageProvider } from "@/contexts/LanguageContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="bn">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* hot Toaster  */}
        <Toaster />

        <LanguageProvider>
          <TanStackQueryWrapper>
            <TooltipProvider>
              <AntdRegistry>{children}</AntdRegistry>
            </TooltipProvider>
          </TanStackQueryWrapper>
        </LanguageProvider>
      </body>
    </html>
  );
}
